title: Materials Genome Foundation Strategic Plan  # The title of the book. Will be placed in the left navbar.
author: The Materials Genome Foundation  # The author of the book
copyright: "2023"  # Copyright year to be placed in the footer
logo: _static/logo-128.png

html:
  use_multitoc_numbering: false
sphinx:
  config:
    latex_documents: 
    - - strategic-plan/README
      - "MGF-Strategic-Plan.tex"
      - Strategic Plan
      - Materials Genome Foundation
      - report
    html_favicon: _static/logo-32.png
    html_theme_options:
      show_nav_level: 2
      collapse_navigation: yes
      announcement: |
        <p>⚠️ The MGF Strategic Plan is in active development. We value all feedback as we devise our first strategic plan.⚠️</p>
        <p>You can help us today by taking our <a href="https://forms.gle/XgT7ZD4p2yH47i1a7">MGF Open Science Survey</a>.</p>
    html_static_path:
    - _static
