title: Strategic Plan  # The title of the book. Will be placed in the left navbar.
author: The Materials Genome Foundation  # The author of the book
copyright: "2023"  # Copyright year to be placed in the footer