on:
- push
jobs:
  pypi:
    strategy:
      matrix:
        python-version:
        - "3.10"
    runs-on: ubuntu-latest
    steps:
    
    - name: fetch all history and tags
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
        cache: pip
        cache-dependency-path: pyproject.toml
        python-version: "${{ matrix.python-version}}"
    - name: install hatch
      run: |
        python -m pip install hatch
    - name: build html
      run: |
        hatch run task:html
    - name: build pdf
      run: |
        hatch run task:pdf
        cp MGF-Strategic-Plan.pdf mgf_strategic_plan/_build/html
    - name: Deploy main 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      # if: ${{ github.ref_name == 'main' }}
      with:
        folder:  mgf_strategic_plan/_build/html
        single-commit: true
